### ISSUE TITLE
Franklin County has too few commerical properties. 

### ISSUE THREAD

**Issue by walinchus** [ludstuen90/property_project_ohio#167] opened 2019-07-31 21:10 UTC
Hmm. Franklin county has 45,638 commercial properties, 11,230 of which are those land use codes in the 400s that we had hoped to scrape for mortgages. 

But for whatever reason, the database only has ~800 commercial properties, without even filtering for the 400s or the ones that actually have a mortgage listed.

**Comment by walinchus** [comment] 2019-08-06 16:33
Just wanted to bring this to your attention again. When you mentioned the Franklin date recorded issue last weekend, I forgot to ask you about this as well. 

So essentially there should be about 11 thousand properties in the database that are Franklin County properties in the 400 land use codes- apartments, hotels, nursing homes, etc. But for whatever reason we have about 800 instead.

**Comment by ludstuen90** [comment] 2019-08-09 00:56
Imported most recent copy of database, and conducted analysis. 

It appears as though a significant number (More than 90 percent) of the properties in the hotels file haven't been scraped yet. Looking to set up a time to take a look at the code running on Lucia's computer. 

One parcel number appeared to have been scraped on July 27, 2019, but didn't have any data associated with it. However, when that same property was scraped on my computer, the property appeared to scrape successfully. (010043618)

Another property I searched appeared to have not been imported successfully from the CSV file when I conducted the analysis.

**Comment by ludstuen90** [comment] 2019-08-11 15:56
Root cause: Property land use code is stored in a different scraper, not the mortgage scraper, which had not completed running.

Solution: Land use codes exist in initial CSV files. Updated code to import land use when importing properties for the first time, and re-ran the initial property csv downloader. 

Reassigning to Lucia to close if OK!

**Closed** 2019-08-11 19:31 UTC
